Repository YAPP-Github/26th-App-Team-2-BE, pull requests merged in 2025-07, with the labels that each got.

#31 fix: 누락 코드 복원
  src/main/kotlin/com/yapp/brake/common/filter/JwtAuthenticationFilter.kt
Labels: 🚨 HotFix

#35 [Fix] 애플 탈퇴 방식 변경
  .gitignore
  src/main/kotlin/com/yapp/brake/auth/dto/request/OAuthWithdrawRequest.kt
  src/main/kotlin/com/yapp/brake/auth/service/AuthService.kt
  src/main/kotlin/com/yapp/brake/auth/service/AuthUseCase.kt
  src/main/kotlin/com/yapp/brake/member/infrastructure/jpa/MemberEntity.kt
  src/main/kotlin/com/yapp/brake/member/service/MemberService.kt
  src/main/kotlin/com/yapp/brake/oauth/model/OAuthUserInfo.kt
  src/main/kotlin/com/yapp/brake/oauth/service/OAuthProvider.kt
  src/main/kotlin/com/yapp/brake/oauth/service/apple/AppleAuthProvider.kt
  src/main/kotlin/com/yapp/brake/oauth/service/apple/AppleTokenProvider.kt
  src/main/kotlin/com/yapp/brake/oauth/service/kakao/KakaoAuthProvider.kt
  src/main/resources/db/migration/V20250711.27__rename_auth.sql
  src/test/kotlin/com/yapp/brake/auth/service/AuthServiceTest.kt
  src/test/kotlin/com/yapp/brake/member/service/MemberServiceTest.kt
  src/test/kotlin/com/yapp/brake/oauth/service/apple/AppleAuthProviderTest.kt
  src/test/kotlin/com/yapp/brake/oauth/service/kakao/KakaoAuthProviderTest.kt
Labels: ⚙️ Fix

#38 [CHORE] Github 이슈 Jira 연동 플로우
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: 🧹Chore

#46 [Refactor] 시큐리티 필터 체인 분리
  .github/ISSUE_TEMPLATE/issue-form.yml
  src/main/kotlin/com/yapp/brake/common/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/com/yapp/brake/common/security/config/SecurityConfig.kt
Labels: 🎨 Refactor

#58 [Fix] RestDocs DSL rest-docs-api-spec 라이브러리 사용하도록 수정
  src/main/kotlin/com/yapp/brake/common/constants/GlobalConstants.kt
  src/test/kotlin/com/yapp/brake/auth/controller/AuthControllerTest.kt
  src/test/kotlin/com/yapp/brake/member/controller/MemberControllerTest.kt
  src/test/kotlin/com/yapp/brake/session/controller/SessionControllerTest.kt
  src/test/kotlin/com/yapp/brake/support/restdocs/Field.kt
  src/test/kotlin/com/yapp/brake/support/restdocs/Param.kt
  src/test/kotlin/com/yapp/brake/support/restdocs/RestDocsUtils.kt
  src/test/kotlin/com/yapp/brake/support/restdocs/SnippetBuilderDsl.kt
Labels: 🐞Bug, ⚙️ Fix

#63 [Feat] HOLD 상태 유저 필터 추가
  src/main/kotlin/com/yapp/brake/auth/service/JwtTokenProvider.kt
  src/main/kotlin/com/yapp/brake/common/constants/GlobalConstants.kt
  src/main/kotlin/com/yapp/brake/common/filter/MemberStateFilter.kt
  src/main/kotlin/com/yapp/brake/common/security/config/SecurityConfig.kt
  src/test/kotlin/com/yapp/brake/auth/service/JwtTokenProviderTest.kt
Labels: ✨Feat
